/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupReposRouteImport } from './routes/setup.repos'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos.$owner.$repo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupReposRoute = SetupReposRouteImport.update({
  id: '/setup/repos',
  path: '/setup/repos',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/repos/$owner/$repo',
  path: '/repos/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup/repos': typeof SetupReposRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup/repos': typeof SetupReposRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup/repos': typeof SetupReposRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/setup/repos' | '/repos/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setup/repos' | '/repos/$owner/$repo'
  id: '__root__' | '/' | '/setup/repos' | '/repos/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupReposRoute: typeof SetupReposRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/repos': {
      id: '/setup/repos'
      path: '/setup/repos'
      fullPath: '/setup/repos'
      preLoaderRoute: typeof SetupReposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupReposRoute: SetupReposRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
