#!/usr/bin/env bun
/**
 * Embeds skills/folio/** into packages/cli/src/skill-bundle.gen.ts at build time.
 *
 * The generated file is gitignored — it is regenerated on every build so the
 * CLI's embedded copy always matches the repo's current skill, content-agnostic.
 * Run via `bun run scripts/embed-skill.ts` (see package.json `build` script).
 */
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const CLI_ROOT = join(import.meta.dir, "..");
const REPO_ROOT = join(CLI_ROOT, "..", "..");
const SKILL_DIR = join(REPO_ROOT, "skills", "folio");
const OUT_FILE = join(CLI_ROOT, "src", "skill-bundle.gen.ts");
const PKG_FILE = join(CLI_ROOT, "package.json");

/** Recursively list files under `dir`, returned as paths relative to `base`. */
function walk(dir: string, base: string, out: string[] = []): string[] {
	for (const entry of readdirSync(dir)) {
		const abs = join(dir, entry);
		const stat = statSync(abs);
		if (stat.isDirectory()) {
			walk(abs, base, out);
		} else if (stat.isFile()) {
			out.push(relative(base, abs).split("\\").join("/"));
		}
	}
	return out;
}

/**
 * Stamp `metadata.folio-cli-version` into a SKILL.md frontmatter block using
 * plain line-level string handling (no YAML parser), so the rest of the
 * frontmatter stays byte-identical.
 */
function stampVersion(content: string, version: string): string {
	const lines = content.split("\n");
	if (lines[0]?.trim() !== "---") return content; // no frontmatter, leave untouched

	let end = -1;
	for (let i = 1; i < lines.length; i++) {
		if (lines[i]?.trim() === "---") {
			end = i;
			break;
		}
	}
	if (end === -1) return content; // malformed frontmatter, leave untouched

	let metadataLine = -1;
	for (let i = 1; i < end; i++) {
		if (/^metadata:\s*$/.test(lines[i] as string)) {
			metadataLine = i;
			break;
		}
	}

	if (metadataLine === -1) {
		// No metadata block: append one at the end of the frontmatter.
		lines.splice(end, 0, "metadata:", `  folio-cli-version: ${version}`);
		return lines.join("\n");
	}

	// metadata block exists — find its extent (indented lines that follow it).
	let blockEnd = metadataLine + 1;
	while (blockEnd < end && /^\s+\S/.test(lines[blockEnd] as string)) {
		blockEnd++;
	}

	let versionLine = -1;
	for (let i = metadataLine + 1; i < blockEnd; i++) {
		if (/^\s+folio-cli-version:\s*/.test(lines[i] as string)) {
			versionLine = i;
			break;
		}
	}

	if (versionLine !== -1) {
		lines[versionLine] = `  folio-cli-version: ${version}`;
	} else {
		lines.splice(blockEnd, 0, `  folio-cli-version: ${version}`);
	}

	return lines.join("\n");
}

const pkg = JSON.parse(readFileSync(PKG_FILE, "utf-8")) as { version: string };
const files = walk(SKILL_DIR, SKILL_DIR).sort();

const entries: Record<string, string> = {};
for (const rel of files) {
	const abs = join(SKILL_DIR, rel);
	let content = readFileSync(abs, "utf-8");
	if (rel === "SKILL.md") {
		content = stampVersion(content, pkg.version);
	}
	entries[rel] = content;
}

const banner = [
	"// AUTO-GENERATED by scripts/embed-skill.ts — do not edit by hand.",
	"// Regenerated on every `bun run build`; not committed to git.",
	"",
].join("\n");

const body = `${banner}export const skillBundle: Record<string, string> = ${JSON.stringify(
	entries,
	null,
	"\t",
)};\n`;

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, body, "utf-8");

console.log(`embed-skill: wrote ${files.length} file(s) to ${relative(REPO_ROOT, OUT_FILE)}`);
